/*****************************************************
*  
*  Copyright 2009 Adobe Systems Incorporated.  All Rights Reserved.
*  
*****************************************************
*  The contents of this file are subject to the Mozilla Public License
*  Version 1.1 (the "License"); you may not use this file except in
*  compliance with the License. You may obtain a copy of the License at
*  http://www.mozilla.org/MPL/
*   
*  Software distributed under the License is distributed on an "AS IS"
*  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
*  License for the specific language governing rights and limitations
*  under the License.
*   
*  
*  The Initial Developer of the Original Code is Adobe Systems Incorporated.
*  Portions created by Adobe Systems Incorporated are Copyright (C) 2009 Adobe Systems 
*  Incorporated. All Rights Reserved. 
*  
*****************************************************/
package org.osmf.elements.f4mClasses
{
	import flexunit.framework.TestCase;
	
	import org.osmf.events.ParseEvent;

	public class TestBootstrapInfoParser extends TestCase
	{
		private var parser:BootstrapInfoParser;
		
		public function testBootstrapInfoParser():void
		{					
			var test:XML =   <bootstrapInfo
								 profile="named"
								 id="bootstrap9532"
							>
								AAAI42Fic3QAAAAAAAAAbwAAAAPoAAAAAAAJGeIAAAAAAAAAAAAAAAAAAQAAAaFhc3J0AAAAAAAAAAAyAAAAAQAAAAMAAAACAAAAAwAAAAMAAAADAAAABAAAAAMAAAAFAAAAAwAAAAYAAAADAAAABwAAAAMAAAAIAAAAAwAAAAkAAAADAAAACgAAAAMAAAALAAAAAwAAAAwAAAADAAAADQAAAAMAAAAOAAAAAwAAAA8AAAADAAAAEAAAAAMAAAARAAAAAwAAABIAAAADAAAAEwAAAAMAAAAUAAAAAwAAABUAAAADAAAAFgAAAAMAAAAXAAAAAwAAABgAAAADAAAAGQAAAAMAAAAaAAAAAwAAABsAAAADAAAAHAAAAAMAAAAdAAAAAwAAAB4AAAADAAAAHwAAAAMAAAAgAAAAAwAAACEAAAADAAAAIgAAAAMAAAAjAAAAAwAAACQAAAADAAAAJQAAAAMAAAAmAAAAAwAAACcAAAADAAAAKAAAAAMAAAApAAAAAwAAACoAAAADAAAAKwAAAAMAAAAsAAAAAwAAAC0AAAADAAAALgAAAAMAAAAvAAAAAwAAADAAAAADAAAAMQAAAAMAAAAyAAAAAwEAAAcWYWZydAAAAAAAAAPoAAAAAHAAAAABAAAAAAAAAAAAABAEAAAAAwAAAAAAACA6AAATiAAAAAQAAAAAAAAz6wAADzwAAAAFAAAAAAAAQw4AABAEAAAABgAAAAAAAFMrAAAMgAAAAAcAAAAAAABfigAAEAQAAAAMAAAAAAAAsBsAAA+gAAAADQAAAAAAAL/lAAAQBAAAAA4AAAAAAADQAgAACvAAAAAPAAAAAAAA2sAAABDMAAAAEAAAAAAAAOtaAAATiAAAABEAAAAAAAD+uAAAEAQAAAASAAAAAAABDtUAAA1IAAAAEwAAAAAAARwEAAAQzAAAABQAAAAAAAEsngAAC7gAAAAVAAAAAAABOIAAABAEAAAAFwAAAAAAAVi6AAAR+AAAABgAAAAAAAFqoQAAEAQAAAAZAAAAAAABer4AABBoAAAAGwAAAAAAAZt1AAAK8AAAABwAAAAAAAGmMwAAEAQAAAAdAAAAAAABtlAAABH4AAAAHgAAAAAAAchhAAAPPAAAAB8AAAAAAAHXrgAAEAQAAAAgAAAAAAAB58sAAA1IAAAAIQAAAAAAAfUjAAAQBAAAACUAAAAAAAI1lwAAEMwAAAAmAAAAAAACRoUAABAEAAAAJwAAAAAAAlaiAAAK8AAAACgAAAAAAAJhYAAAEGgAAAApAAAAAAACcaYAABGUAAAAKgAAAAAAAoNkAAAM5AAAACsAAAAAAAKQaQAAEMwAAAAsAAAAAAACoS0AAA7YAAAALQAAAAAAArAmAAARMAAAAC4AAAAAAALBPQAAEAQAAAAwAAAAAAAC4U4AAA1IAAAAMQAAAAAAAu59AAASwAAAADIAAAAAAAMBXgAAEMwAAAAzAAAAAAADEiIAAArwAAAANAAAAAAAAxzgAAATJAAAADUAAAAAAAMv6wAAEGgAAAA2AAAAAAADQDEAAA2sAAAANwAAAAAAA04HAAAPoAAAADgAAAAAAANdfQAAElwAAAA5AAAAAAADb7gAAA7YAAAAOgAAAAAAA36xAAANrAAAADsAAAAAAAOMNAAAEAQAAAA9AAAAAAADrG4AABBoAAAAPgAAAAAAA7y0AAAQBAAAAD8AAAAAAAPM0QAAC7gAAABAAAAAAAAD2IkAABJcAAAAQQAAAAAAA+ruAAAQaAAAAEIAAAAAAAP7NAAADOQAAABDAAAAAAAECDoAABJcAAAARAAAAAAABBqeAAAQaAAAAEUAAAAAAAQq5QAAC1QAAABGAAAAAAAENiAAABPsAAAARwAAAAAABEolAAALuAAAAEgAAAAAAARWBgAAElwAAABJAAAAAAAEaGsAAA1IAAAASgAAAAAABHWaAAASXAAAAEsAAAAAAASH/gAAEMwAAABMAAAAAAAEmOsAAArwAAAATQAAAAAABKOpAAAPoAAAAE4AAAAAAASzIAAAEZQAAABPAAAAAAAExLQAABJcAAAAUAAAAAAABNcYAAANSAAAAFEAAAAAAATkcQAAEZQAAABSAAAAAAAE9gUAABAEAAAAUwAAAAAABQYiAAAK8AAAAFQAAAAAAAUQ4AAAEyQAAABVAAAAAAAFJBQAABDMAAAAVgAAAAAABTSuAAAQBAAAAFcAAAAAAAVEywAACvAAAABYAAAAAAAFT4kAABAEAAAAXgAAAAAABbAOAAAPoAAAAF8AAAAAAAW/1wAAEMwAAABgAAAAAAAF0MUAABBoAAAAYQAAAAAABeE1AAAK8AAAAGIAAAAAAAXr8wAAEAQAAABjAAAAAAAF/BAAAA+gAAAAZAAAAAAABguGAAATiAAAAGUAAAAAAAYe5QAADzwAAABmAAAAAAAGLggAAAyAAAAAZwAAAAAABjpmAAAPoAAAAGkAAAAAAAZZpgAADzwAAABqAAAAAAAGaPMAABDMAAAAawAAAAAABnm3AAARlAAAAGwAAAAAAAaLdAAADOQAAABtAAAAAAAGmFAAAA+gAAAAbgAAAAAABqfwAAAQBAAAAG8AAAAAAAa4DQAAEMwAAABwAAAAAAAGyNEAABEwAAAAcQAAAAAABtoRAAAQBAAAAHMAAAAAAAb6SwAADtgAAAB0AAAAAAAHCRsAABAEAAAAdgAAAAAABylVAAANSAAAAHcAAAAAAAc2rgAAEMwAAAB4AAAAAAAHR3EAAAyAAAAAeQAAAAAAB1PQAAATiAAAAHoAAAAAAAdnggAADtgAAAB7AAAAAAAHdnsAABAEAAAAfQAAAAAAB5a1AAAK8AAAAH4AAAAAAAehcwAAEAQAAACIAAAAAAAIQpUAAArwAAAAiQAAAAAACE1TAAAQBAAAAJEAAAAAAAjOOwAADzwAAACSAAAAAAAI3V4AABAEAAAAlQAAAAAACQ21AAAK8AAAAJYAAAAAAAkYcwAAAZAAAAAAAAAAAAAAAAAAAAAAAA==
							</bootstrapInfo>;
			
			parser = new BootstrapInfoParser();
			parser.addEventListener(ParseEvent.PARSE_COMPLETE, addAsync(verifyParse, 1000));
			parser.parse(test.toXMLString());
		}
		
		private function verifyParse(event:ParseEvent):void
		{
			var bootstrapInfo:BootstrapInfo = event.data as BootstrapInfo;
			
			assertNotNull(bootstrapInfo);
			assertEquals("bootstrap9532", bootstrapInfo.id);
			assertEquals("named", bootstrapInfo.profile);
			assertNotNull(bootstrapInfo.data);
		}
		
		public function testNoProfile():void
		{
			parser = new BootstrapInfoParser();
			
			var errorSeen:Boolean = false;
			var test:XML = <bootstrapInfo url="/mybootstrapinfo"/>;
			
			try
			{
				parser.parse(test.toXMLString());			
			}
			catch(error:ArgumentError)
			{
				errorSeen = true;
			}
			
			assertTrue(errorSeen);
		}
	}
}