/**
*This file is automatically generated by Flash Builder to compile FlexUnit classes and is not intended for modification.
*Please click on the "Refresh" icon in "FlexUnit Results" view to regenerate this file.
*/

package
{
	import flash.display.Sprite;
	
	import org.osmf.media.videoClasses.TestStageVideoManager;
	
	public class FlexUnitCompilerApplication extends Sprite
	{
		
		private var org_osmf_media_videoClasses_TestStageVideoManager_obj:org.osmf.media.videoClasses.TestStageVideoManager;
	}
}